# see: http://about.travis-ci.org/docs/user/languages/python/
language: python
#python:
  #- 2.7
  #- 3.4
  #- 3.5
  #- 3.6
# see: http://docs.travis-ci.com/user/caching/#pip-cache
cache: pip
# see: http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-devel
    - python: 3.6
      env: TOXENV=py36-devel
    # https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
    - python: 3.7
      env: TOXENV=py37-devel
      sudo: required
      dist: xenial
env:
  global:
    - WITH_COVERAGE=1
    - WITH_DEPS=true
install:
  - pip install --yes tox
script:
  - tox
after_success:
  - coveralls
notifications:
  email:
    recipients:
      - satoru.satoh+github@gmail.com
    on_failure: always
