---
# yamllint disable rule:line-length
# .. seealso:: https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
name: Release
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
    tags:
      - 'RELEASE*'
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Build distribution archives
        run: tox -e dists
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags') || github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

# vim:sw=2:ts=2:et:
